import os

header = open("include/rayscenes.hpp", "r")
headerText = header.readlines()
while headerText[0].startswith("//"):
    headerText.pop(0)

src = open("src/rayscenes.cpp", "r")
srcText = src.readlines()
while srcText[0].startswith("//"):
    srcText.pop(0)

out = open("rayscenes.hpp", "w+")

out.write(
f"""//
// Autogenerated single header file for rayscenes
// Licensed under the Apache License, Version 2.0
// See the LICENSE file in the project root for more information
// © Winter/Vortetty 2021 
//

{"".join(headerText)}

#ifdef RAYSCENES_IMPLEMENTATION
{"".join(srcText)}
#endif\n"""
)

header.close()
src.close()
out.close()

os.system("clang-format -i rayscenes.hpp")
